### ISSUE TITLE
Support the Citation File Format

### ISSUE THREAD

**Issue by sdruskat** [ropensci/handlr#16]
The [Citation File Format](https://citation-file-format.github.io/) is a human- and machine-readable and -writable format implemented in YAML to provide citation-relevant metadata for software. It has been conceived to make it possible for developers to provide the correct citation metadata for their software, and for users to gain access to the relevant information quickly. Its implementation takes into account the [Software Citation Principles](https://peerj.com/articles/cs-86/) through requiring the necessary minimal information where feasible.

It would be great if `handlr` supported this format as well, most importantly as source, perhaps also as target format.

I'll be happy to put some work into this, but as I'm an R newbie may need some help. 

If this is something that the project finds useful, I'd start with looking at the available readers and try my hand at implementing a reader for CFF. This could possibly be done as part of the [CollabW19](https://www.software.ac.uk/cw19) hack day.

Please let me know your thoughts on this.

**Comment by sckott** [comment]
Thanks @sdruskat for the issue - I somehow hadn't seen this format 😬 

You are very welcome to send a PR, or make it part of CollabW19. I'm happy to help whether you do it, or anyone working on it at CollabW19. And do let me know at some point if you don't think it will be done and I can take a whack at it

**Comment by sckott** [comment]
started working on this. 

- would be nice to see how folks convert cff to other citation formats, e.g., bibtex - what fields map to what fields
- is it possible to have many citations in one file or not? asked in issue linked above
- it'd be nice not to have to use the yaml pkg as its buggy, but probably better not to try to parse yaml manually

**Comment by sdruskat** [comment]
Sorry for the late reply. As for your questions:

- To see how other tools convert to other formats, you could have a look at [cffconvert](https://github.com/citation-file-format/cff-converter-python), which is a Python tool to convert CFF to several formats, including BibTeX.
- Multiple citations: Yes and no. The root citation metadata is always for the *software itself* that the metadata is provided for in the CFF file. References to spin-off/related products such as papers describing the software can be added as a reference in the `references` list in CFF.
- `yaml` package: I guess this is the R package you're referring to. No experience on my end, so I'm afraid I have no suggestions here.

Closing https://github.com/citation-file-format/citation-file-format/issues/107 now, but please feel free to ping me in this issue here (or open a new issue in the CFF repo) should there be more questions.

**Comment by sckott** [comment]
Okay, thanks for the responses. Makes sense on the multiple citations question.

**Comment by sckott** [comment]
to do:
- [ ] support many references in one citation file - but each file only has the one citation
- [ ] sort out how to convert cff to other citation formats, at least for some
